In [1]:
import pandas as pd

# Load the CSV dataset
df = pd.read_csv("Loan_default.csv")

# Define mappings for each non-numeric column
education_mapping = {
    "Bachelor's": 1,
    "High School": 2,
    "PhD": 3,
    "Master's": 4,
    
    
}

employment_mapping = {
    "Full-time": 1,
    "Part-time": 2,
    "Unemployed": 3,
    "Self-employed": 4,
   
}

marital_status_mapping = {
    "Single": 1,
    "Married": 2,
    "Divorced": 3,
   
}

has_mortgage_mapping = {
    "No": 0,
    "Yes": 1,
}

has_dependents_mapping = {
    "No": 0,
    "Yes": 1,
}

loan_purpose_mapping = {
    "Other": 1,
    "Auto": 2,
    "Business": 3,
    "Education": 4,
    "Home": 5,
   
}

has_co_signer_mapping = {
    "No": 0,
    "Yes": 1,
}

# Apply the mappings to the respective columns
df['Education'] = df['Education'].map(education_mapping)
df['EmploymentType'] = df['EmploymentType'].map(employment_mapping)
df['MaritalStatus'] = df['MaritalStatus'].map(marital_status_mapping)
df['HasMortgage'] = df['HasMortgage'].map(has_mortgage_mapping)
df['HasDependents'] = df['HasDependents'].map(has_dependents_mapping)
df['LoanPurpose'] = df['LoanPurpose'].map(loan_purpose_mapping)
df['HasCoSigner'] = df['HasCoSigner'].map(has_co_signer_mapping)

# Save the modified dataset to a new CSV file
df.to_csv("Loan_default_numeric.csv", index=False)

# Display the first few rows of the modified dataset
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,1,1,3,1,1,1,1,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,4,1,2,0,0,1,1,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,4,3,3,1,1,2,0,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,2,1,2,0,0,3,0,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,1,3,3,0,1,2,0,0